### ISSUE TITLE
docs missing

### ISSUE THREAD

**Issue by Mohl** [dockhippie/mywebsql#1]
Is there a documentation for this docker image somewhere? I'd love to have a list of options for the env variables.

**Comment by tboerger** [comment]
There is not really any documentation for this image yet, the env variables are more or less directly mapped to the mywebsql configuration file.

**Comment by tboerger** [comment]
That's how I'm running it locally: `docker run -d --restart=always --name mywebsql -e MYWEBSQL_SERVER_LIST=mysqli:mariadb -p 8080:8080 --link mariadb:mariadb webhippie/mywebsql:latest`
