### ISSUE TITLE
Does not seem to work correctly behind a reverse proxy that changes the URL

### ISSUE THREAD

**Issue by dm-rfraser** [dockhippie/mywebsql#2]
For example, using docker-compose, spin up an nginx that redirects all paths starting with `/pma` to the server, like so:

```
location /pma/ {
  proxy_pass http://mywebsql:8080;
  proxy_set_header Host $host;
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Host $server_name;
}
```

The login page shows up fine, but after login, all the styles and links are broken, since they use paths relative to the root.

**Comment by tboerger** [comment]
I can't find any option at https://github.com/Samnan/MyWebSQL/tree/master/config to configure the path of the application, so looks like upstream doesn't support it. You should ask upstream for support for that.
